trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm i -D typescript@4.1.5
  displayName: 'Install Dependencies'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run build -- --prod
  displayName: 'Build Web App'

- task: CopyFiles@2
  displayName: 'Copy Files to artifact staging directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\www'
    Contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
- upload: $(Build.ArtifactStagingDirectory)
  artifact: drop

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'cpanel-skiplineweb'
    sourceFolder: '$(Build.SourcesDirectory)\www'
    contents: '**'
    targetFolder: '/home/v8vz4cxnet5n/public_html'
    readyTimeout: '20000'